---
- name: Purge detection directories
  ansible.windows.win_powershell:
    script: |
      if (Test-Path "C:\Tools\Detect\*") { Get-ChildItem "C:\Tools\Detect\*" | Where-Object { $_.Name -ine "yara" } | Remove-Item -Recurse -Force }
      if (Test-Path "C:\Tools\Detect\yara\*") { Remove-Item "C:\Tools\Detect\yara\*" -Recurse -Force }

- name: Install detect tools (git)
  ansible.windows.win_command: |
    git clone {{ item }}
  args:
    chdir: "C:\\Tools\\Detect"
  loop: "{{ detect_repos | default([]) }}"
  when: detect_repos is defined and detect_repos | length > 0

- name: Copying the YARA install script
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/yara.bat"
    dest: 'C:\Tools\Detect\yara\yara.bat'

- name: Install YARA and YARA detection rules
  ansible.windows.win_shell: C:\Tools\Detect\yara\yara.bat . install
  args:
    chdir: "C:\\Tools\\Detect\\yara"

- name: Install sysmon
  ansible.windows.win_powershell:
    script: |
      $ErrorActionPreference = 'Stop'
      Invoke-WebRequest -Uri 'https://download.sysinternals.com/files/Sysmon.zip' -OutFile 'C:\Windows\Temp\Deployment\sysmon.zip'
      Expand-Archive -Path 'C:\Windows\Temp\Deployment\sysmon.zip' -DestinationPath 'C:\Tools\Detect\sysmon' -Force
      Invoke-WebRequest -Uri 'https://raw.githubusercontent.com/SwiftOnSecurity/sysmon-config/refs/heads/master/sysmonconfig-export.xml' -OutFile 'C:\Tools\Detect\sysmon\sysmon-swiftonsecurity.xml'

- name: Copy ConfuserEx2.zip to C:\Tools\RE
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/tools/ConfuserEx2.zip"
    dest: "C:\\Tools\\RE\\ConfuserEx2.zip"

- name: Unzip ConfuserEx2.zip
  community.windows.win_unzip:
    src: "C:\\Tools\\RE\\ConfuserEx2.zip"
    dest: "C:\\Tools\\RE\\ConfuserEx2\\"
    remote_src: true

- name: Remove ConfuserEx2.zip after extraction
  ansible.windows.win_file:
    path: "C:\\Tools\\RE\\ConfuserEx2.zip"
    state: absent

- name: Copy EVTX.zip to C:\Tools\Others
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/tools/EVTX.zip"
    dest: "C:\\Tools\\Others\\EVTX.zip"

- name: Unzip EVTX.zip
  community.windows.win_unzip:
    src: "C:\\Tools\\Others\\EVTX.zip"
    dest: "C:\\Tools\\Others\\EVTX\\"
    remote_src: true

- name: Remove EVTX.zip after extraction
  ansible.windows.win_file:
    path: "C:\\Tools\\Others\\EVTX.zip"
    state: absent

- name: Create Desktop analyse folder
  ansible.windows.win_file:
    path: "C:\\Users\\{{ ansible_user_id }}\\Desktop\\analyse"
    state: directory
