---
- name: System preparation
  ansible.builtin.include_tasks:
    file: prepare.yml

- name: Install Chocolatey tooling
  ansible.builtin.include_tasks:
    file: install_choco.yml

- name: Install other tooling
  ansible.builtin.include_tasks:
    file: install_others.yml

- name: Setup shortcuts
  ansible.builtin.include_tasks:
    file: setup_shortcuts.yml

- name: User customization
  ansible.builtin.include_tasks:
    file: user.yml

- name: Copy the INSTALLED.txt file onto the system
  ansible.windows.win_copy:
    src: "{{ role_path }}/files/INSTALLED.txt"
    dest: 'C:\Tools\INSTALLED.txt'

- name: Reboot
  ansible.windows.win_reboot:
    reboot_timeout: 300
