---
- name: Create 'C:\Payloads', 'C:\Tools' and other directories
  win_file:
    path: "{{ directories }}"
    state: directory
  with_items:
    - C:\Tools
    - C:\Tools\Detect
    - C:\Tools\Detect\yara
    - C:\Tools\Others
    - C:\Tools\RE
  loop_control:
    loop_var: directories

- name: Add the '{{ ludus_user_name }}' user
  win_user:
    name: "{{ ludus_user_name }}"
    password: "{{ ludus_user_password }}"
    description: "Operator user added with Ansible."
    password_never_expires: yes
    user_cannot_change_password: no
    groups:
      - "Administrators"
      - "Remote Desktop Users"
    state: present

- name: Set autologon entries (part 1)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinLogon
    name: AutoAdminLogon
    data: 1
    type: string

- name: Set autologon entries (part 2)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinLogon
    name: DefaultUserName
    data: "{{ ludus_user_name }}"
    type: string

- name: Set autologon entries (part 3)
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion\WinLogon
    name: DefaultPassword
    data: "{{ ludus_user_password }}"
    type: string

- name: Disable Windows Updates
  ansible.builtin.script:
    cmd: disable_updates.ps1

#- name: Disable Defender 1
#  ansible.windows.win_powershell:
#    script: |
#      Add-MpPreference -ExclusionPath 'C:\'

#- name: Execute PowerShell script to check tamper protection status
#  ansible.windows.win_shell: |
#    (Get-MpComputerStatus).IsTamperProtected
#  register: tamper_protection_result

#- name: Set fact based on tamper protection status
#  ansible.builtin.set_fact:
#    tamper_protection_enabled: "{{ true if 'True' in tamper_protection_result.stdout else false }}"

#- name: Disable Defender 2
#  ansible.builtin.script:
#    cmd: disable_defender.bat
#  register: disable_defender
#  when: tamper_protection_enabled

#- name: Reboot after disabling Defender
#  ansible.windows.win_reboot:
#  when: tamper_protection_enabled

- name: Run the debloat script
  ansible.builtin.script:
    cmd: debloat.ps1

- name: Reboot
  ansible.windows.win_reboot:
    reboot_timeout: 300